%Tester for ofdmSymbol and ofdmDemod

% m1 is a 16-QAM symbol (randomly generated by aqm16 fucntion)
% m1 = [0.3162 - 0.9487i   0.3162 - 0.9487i   0.3162 + 0.9487i   0.3162 - 0.9487i   0.9487 - 0.3162i   0.3162 - 0.9487i  -0.9487 - 0.3162i   0.3162 + 0.3162i   0.3162 + 0.3162i -0.9487 - 0.9487i  -0.3162 + 0.3162i   0.9487 - 0.3162i];
% ofdm_s = ofdmSymbol(m1); %generate modulation symbols
% k = input('Enter kth number 0~11:  ');
% symbol = ofdmDemod(k,ofdm_s);
% disp(symbol);

% m2 a QPSK symbol (randomly generated by qpsk fucntion)
m2 = [0.3162 + 0.3162i   0.3162 + 0.3162i  -0.3162 + 0.9487i   0.9487 - 0.3162i   0.9487 - 0.3162i   0.3162 - 0.9487i   0.9487 - 0.3162i   0.3162 - 0.9487i   0.3162 + 0.3162i 0.3162 - 0.9487i   0.9487 - 0.3162i  -0.3162 + 0.9487i];
ofdm_s = ofdmSymbol(m2); %generate modulation symbols
k = input('Enter kth number 0~11:  ');
symbol = ofdmDemod(k,ofdm_s);
disp(symbol);